---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    name: wp-cm
data:
  WORDPRESS_DB_HOST: wpdb-mysql-mysql-master
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: changeit
  WORDPRESS_DB_NAME: wpdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    name: wp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-pod
  template:
    metadata:
      name: wp-pod
      labels:
        app: wp-pod
    spec:
      containers:
      - name: wp-container
        image: wordpress:5.8-apache
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wp-cm
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels: 
    name: wp-svc
spec:
  type: ClusterIP
  selector:
    app: wp-pod
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ing
  labels:
    name: wp-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: wp-188.166.206.210.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wp-svc
            port: 
              number: 80

