---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws2-deploy-db
  labels:
    name: ws2-deploy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ws2-pod-db
  template:
    metadata:
      name: ws2-pod-db
      labels:
        name: ws2-pod-db
    spec:
      containers:
      - name: ws2-container-db
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: ws2-svc-db
  labels:
    name: ws2-svc-db
spec:
  type: ClusterIP
  selector:
    name: ws2-pod-db
  ports:
  - port: 3306
    targetPort: 3306
