---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws2-deploy-backend
  labels:
    name: ws2-deploy-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
  selector:
    matchLabels:
      name: ws2-pod-backend
  template:
    metadata:
      name: ws2-pod-backend
      labels:
        name: ws2-pod-backend
    spec:
      containers:
      - name: ws2-container-backend
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 30
          httpGet: 
            path: /healthz
            port: 3000
        env:
        - name: BGG_DB_USER
          value: root
        - name: BGG_DB_HOST
          value: 10.245.133.237
        envFrom:
        - secretRef:
            name: ws2-secret
        ports:
        - name: port-backend
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ws2-svc-backend
  labels:
    name: ws2-svc-backend
spec:
  type: LoadBalancer
  selector:
    name: ws2-pod-backend
  ports:
  - port: 80
    targetPort: port-backend
